/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sysPTT2;

import static org.junit.Assert.assertNotNull;

import org.junit.Test;

public class AppTest {
    @Test
    public void testAppHasAGreeting() {
	TrayService classUnderTest = new TrayService();
	assertNotNull("TEST here later");
    }
}
